name: firest workflow

on: 
  push:
    branches:
      - main

jobe:
  example-job:
    runs-on: ubuntu-latest    

steps: 
  - name: print welcom massege
    run: echo "hello our github action users"

  - name: Checkout
    uses: actions/checkout@v6.1.0

  - name: list
    run: ls -la
